### ISSUE TITLE
manual run following instructions won't complete

### ISSUE THREAD

**Issue by senrabc** [senrabc/honeyguide#3]
Error:
generating the redcap data database
Using quail.conf.yaml at /home/hcvprod/quailroot/quail.conf.yaml
Loading metadata...
Writing instruments tables...
Traceback (most recent call last):
  File "/usr/local/bin/quail", line 11, in <module>
    load_entry_point('quail', 'console_scripts', 'quail')()
  File "/home/hcvprod/QUAIL/quail/__main__.py", line 104, in cli_run
    main(args)
  File "/home/hcvprod/QUAIL/quail/__main__.py", line 92, in main
    redcap.gen_data(**conf)
  File "/home/hcvprod/QUAIL/quail/actions/redcap.py", line 175, in gen_data
    for instrument in instrumentor.get_all_instruments():
  File "/home/hcvprod/QUAIL/quail/utils/redcap_util/redcap_sqlize.py", line 115, in get_all_instruments
    return [self.get_instrument_table(name) for name in self.instruments]
  File "/home/hcvprod/QUAIL/quail/utils/redcap_util/redcap_sqlize.py", line 115, in <listcomp>
    return [self.get_instrument_table(name) for name in self.instruments]
  File "/home/hcvprod/QUAIL/quail/utils/redcap_util/redcap_sqlize.py", line 110, in get_instrument_table
    in self.fields_for_instrument(instrument_name)
  File "/home/hcvprod/QUAIL/quail/utils/redcap_util/redcap_sqlize.py", line 111, in <listcomp>
    if self.is_lookup_field(field)]
  File "/home/hcvprod/QUAIL/quail/utils/redcap_util/redcap_sqlize.py", line 77, in is_lookup_field
    field = self.get_field(field_name)
  File "/home/hcvprod/QUAIL/quail/utils/redcap_util/redcap_sqlize.py", line 72, in get_field
    raise Exception('too many matching fields for %s' % field_name)
Exception: too many matching fields for redcap_event_name
NOTICE:  database "latest" does not exist, skipping
DROP DATABASE
making a new postgres database
CREATE DATABASE
CREATE DATABASE
CREATE ROLE
GRANT
GRANT
loading the databases
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.

**Comment by PFWhite** [comment]
I think that this issue is actually a symptom rather than a cause, although the error is not the best. I have been able to replicate this bug but it is due to REDCap failing to deliver data. The exception that is being thrown is over specified.

**Comment by senrabc** [comment]
As you saw the data.db was 0 bytes.

**Comment by PFWhite** [comment]
If you pull QUAIL from my master branch this is fixed. I believe there is a pull request still out to update ctsit's quail

**Comment by PFWhite** [comment]
fixed pending code review
